
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EldocCodeApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Message
{

    public int Id { get; set; }

    public System.DateTime SendDate { get; set; }

    public string Text { get; set; }

    public Nullable<int> ClientId { get; set; }

    public Nullable<int> WorkerId { get; set; }

    public int ChatId { get; set; }



    public virtual Chat Chat { get; set; }

    public virtual Client Client { get; set; }

    public virtual Worker Worker { get; set; }

}

}
