

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EldocCodeApi.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class EldoCodeEntities : DbContext
{
    public EldoCodeEntities()
        : base("name=EldoCodeEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Category> Category { get; set; }

    public virtual DbSet<Chat> Chat { get; set; }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Country> Country { get; set; }

    public virtual DbSet<Firm> Firm { get; set; }

    public virtual DbSet<Message> Message { get; set; }

    public virtual DbSet<Notification> Notification { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<ProductOrder> ProductOrder { get; set; }

    public virtual DbSet<Region> Region { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<Status> Status { get; set; }

    public virtual DbSet<Store> Store { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Worker> Worker { get; set; }

}

}

