
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EldocCodeApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {

        this.ProductOrder = new HashSet<ProductOrder>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string VendorCode { get; set; }

    public int CategoryId { get; set; }

    public Nullable<int> FirmId { get; set; }

    public byte[] Photo { get; set; }

    public Nullable<decimal> Price { get; set; }

    public string Description { get; set; }



    public virtual Category Category { get; set; }

    public virtual Firm Firm { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductOrder> ProductOrder { get; set; }

}

}
