
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EldocCodeApi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Store
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Store()
    {

        this.Worker = new HashSet<Worker>();

    }


    public int Id { get; set; }

    public string Address { get; set; }

    public int CountryId { get; set; }

    public int RegionId { get; set; }



    public virtual Country Country { get; set; }

    public virtual Region Region { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Worker> Worker { get; set; }

}

}
